
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class CalculatorTest {

//I used 5 JUnit test to be able to use the assertThrows method.
	
	@Test
	void testAdd() {
		Calculator X = new Calculator();//creating an instance 	
		assertEquals(5,X.add(2, 3));
		assertEquals(2,X.add(-1, 3));
		
		
	}

	@Test
	void testDivide() {
	Calculator Z = new Calculator();//creating an instance 
	assertEquals(2.5,Z.divide(5, 2));
	assertEquals(5,Z.divide(10, 2));
	assertEquals(0.333,Z.divide(1, 3),0.1);//the third parameter is a positive delta 
	assertEquals(0.0,Z.divide(0, -1));
	//Testing if the exception is being thrown or not .
	assertThrows(RuntimeException.class,()->Z.divide(2, 0));
		
		
		
	}

}
